### ISSUE TITLE
Unreadable font

### ISSUE THREAD

**Issue by iosdev474** [MNNIT/Avishkar#82]
Sir, Avishkar written on homepage at desktop has too much shadow which makes it unreadable in safari.
If its shadow is reduced than website looks awesome.
![screen shot 2018-09-10 at 7 09 18 pm](https://user-images.githubusercontent.com/33452790/45300730-cb5f2980-b52c-11e8-962c-c81adc72dc50.png)

**Rest of website is awesome. 🤘**

**Comment by poornachandugade** [comment]
Can you mention the browser and version you are using.

**Comment by poornachandugade** [comment]
I think the problem should be solved now.
